# Generated by Django 5.2.5 on 2025-10-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
